import type { CardSuit } from "../../core/types";
import type { CardPrint } from "../../core/state";

type PrintRow = readonly [name: string, suit: CardSuit, rank: number];

const STANDARD_PRINT_ROWS: readonly PrintRow[] = [
  ["杀", "spade", 7],
  ["杀", "spade", 8],
  ["杀", "spade", 8],
  ["杀", "spade", 9],
  ["杀", "spade", 9],
  ["杀", "spade", 10],
  ["杀", "spade", 10],
  ["杀", "club", 2],
  ["杀", "club", 3],
  ["杀", "club", 4],
  ["杀", "club", 5],
  ["杀", "club", 6],
  ["杀", "club", 7],
  ["杀", "club", 8],
  ["杀", "club", 8],
  ["杀", "club", 9],
  ["杀", "club", 9],
  ["杀", "club", 10],
  ["杀", "club", 10],
  ["杀", "club", 11],
  ["杀", "club", 11],
  ["杀", "heart", 2],
  ["杀", "heart", 2],
  ["杀", "heart", 13],
  ["杀", "diamond", 6],
  ["杀", "diamond", 7],
  ["杀", "diamond", 8],
  ["杀", "diamond", 9],
  ["杀", "diamond", 10],
  ["杀", "diamond", 13],
  ["闪", "heart", 2],
  ["闪", "heart", 2],
  ["闪", "heart", 13],
  ["闪", "diamond", 2],
  ["闪", "diamond", 2],
  ["闪", "diamond", 3],
  ["闪", "diamond", 4],
  ["闪", "diamond", 5],
  ["闪", "diamond", 6],
  ["闪", "diamond", 7],
  ["闪", "diamond", 8],
  ["闪", "diamond", 9],
  ["闪", "diamond", 10],
  ["闪", "diamond", 11],
  ["闪", "diamond", 11],
  ["桃", "heart", 3],
  ["桃", "heart", 4],
  ["桃", "heart", 6],
  ["桃", "heart", 7],
  ["桃", "heart", 8],
  ["桃", "heart", 9],
  ["桃", "heart", 12],
  ["桃", "diamond", 12],
  ["诸葛连弩", "club", 1],
  ["诸葛连弩", "diamond", 1],
  ["雌雄双股剑", "spade", 2],
  ["青釭剑", "spade", 6],
  ["青龙偃月刀", "spade", 5],
  ["丈八蛇矛", "spade", 12],
  ["贯石斧", "diamond", 5],
  ["方天画戟", "diamond", 12],
  ["麒麟弓", "heart", 5],
  ["八卦阵", "spade", 2],
  ["八卦阵", "club", 2],
  ["绝影", "spade", 5],
  ["的卢", "club", 5],
  ["爪黄飞电", "heart", 13],
  ["赤兔", "heart", 5],
  ["大宛", "spade", 13],
  ["紫骍", "diamond", 13],
  ["五谷丰登", "heart", 3],
  ["五谷丰登", "heart", 4],
  ["桃园结义", "heart", 1],
  ["南蛮入侵", "spade", 7],
  ["南蛮入侵", "spade", 13],
  ["南蛮入侵", "club", 7],
  ["万箭齐发", "heart", 1],
  ["决斗", "spade", 1],
  ["决斗", "club", 1],
  ["决斗", "diamond", 1],
  ["无中生有", "heart", 7],
  ["无中生有", "heart", 8],
  ["无中生有", "heart", 9],
  ["无中生有", "heart", 11],
  ["顺手牵羊", "spade", 3],
  ["顺手牵羊", "spade", 4],
  ["顺手牵羊", "spade", 11],
  ["顺手牵羊", "diamond", 4],
  ["顺手牵羊", "diamond", 1],
  ["过河拆桥", "spade", 3],
  ["过河拆桥", "spade", 4],
  ["过河拆桥", "spade", 12],
  ["过河拆桥", "club", 3],
  ["过河拆桥", "club", 4],
  ["过河拆桥", "heart", 12],
  ["借刀杀人", "club", 12],
  ["借刀杀人", "club", 13],
  ["无懈可击", "spade", 11],
  ["无懈可击", "club", 12],
  ["无懈可击", "club", 13],
  ["乐不思蜀", "spade", 6],
  ["乐不思蜀", "club", 6],
  ["乐不思蜀", "heart", 6],
  ["闪电", "spade", 1],
  ["寒冰剑", "spade", 2],
  ["仁王盾", "club", 2],
  ["闪电", "heart", 12],
  ["无懈可击", "diamond", 12]
];

const MANEUVERING_PRINT_ROWS: readonly PrintRow[] = [
  ["古锭刀", "spade", 1],
  ["藤甲", "spade", 2],
  ["酒", "spade", 3],
  ["雷杀", "spade", 4],
  ["雷杀", "spade", 5],
  ["雷杀", "spade", 6],
  ["雷杀", "spade", 7],
  ["雷杀", "spade", 8],
  ["酒", "spade", 9],
  ["兵粮寸断", "spade", 10],
  ["铁索连环", "spade", 11],
  ["铁索连环", "spade", 12],
  ["无懈可击", "spade", 13],
  ["白银狮子", "club", 1],
  ["藤甲", "club", 2],
  ["酒", "club", 3],
  ["兵粮寸断", "club", 4],
  ["雷杀", "club", 5],
  ["雷杀", "club", 6],
  ["雷杀", "club", 7],
  ["雷杀", "club", 8],
  ["酒", "club", 9],
  ["铁索连环", "club", 10],
  ["铁索连环", "club", 11],
  ["铁索连环", "club", 12],
  ["铁索连环", "club", 13],
  ["无懈可击", "heart", 1],
  ["火攻", "heart", 2],
  ["火攻", "heart", 3],
  ["火杀", "heart", 4],
  ["桃", "heart", 5],
  ["桃", "heart", 6],
  ["火杀", "heart", 7],
  ["闪", "heart", 8],
  ["闪", "heart", 9],
  ["火杀", "heart", 10],
  ["闪", "heart", 11],
  ["闪", "heart", 12],
  ["无懈可击", "heart", 13],
  ["朱雀羽扇", "diamond", 1],
  ["桃", "diamond", 2],
  ["桃", "diamond", 3],
  ["火杀", "diamond", 4],
  ["火杀", "diamond", 5],
  ["闪", "diamond", 6],
  ["闪", "diamond", 7],
  ["闪", "diamond", 8],
  ["酒", "diamond", 9],
  ["闪", "diamond", 10],
  ["闪", "diamond", 11],
  ["火攻", "diamond", 12],
  ["骅骝", "diamond", 13]
];

function createPrints(
  rows: readonly PrintRow[],
  idsByName: Readonly<Record<string, string>>
): CardPrint[] {
  return rows.map(([name, suit, rank]) => {
    const definitionId = idsByName[name];
    if (!definitionId) {
      throw new Error(`deck row references unknown card name: ${name}`);
    }
    return { definitionId, suit, rank };
  });
}

export function createStandardPrints(
  idsByName: Readonly<Record<string, string>>
): CardPrint[] {
  return createPrints(STANDARD_PRINT_ROWS, idsByName);
}

export function createManeuveringPrints(
  idsByName: Readonly<Record<string, string>>
): CardPrint[] {
  return createPrints(MANEUVERING_PRINT_ROWS, idsByName);
}
