/*
 * 数据文件
 * ♠ 3
 * ♣ 2
 * ♥ 1
 * ♦ 0
 */

var pattern = [3, 2, 1, 0]; 

var cards = [
    { name: '杀', pattern: 3, num: '7', imgUrl: 'slash.png' },
    { name: '杀', pattern: 3, num: '8', imgUrl: 'slash.png' },
    { name: '杀', pattern: 3, num: '8', imgUrl: 'slash.png' },
    { name: '杀', pattern: 3, num: '9', imgUrl: 'slash.png' },
    { name: '杀', pattern: 3, num: '9', imgUrl: 'slash.png' },
    { name: '杀', pattern: 3, num: '10', imgUrl: 'slash.png' },
    { name: '杀', pattern: 3, num: '10', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '2', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '3', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '4', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '5', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '6', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '7', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '8', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '8', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '9', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '9', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '10', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '10', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '11', imgUrl: 'slash.png' },
    { name: '杀', pattern: 2, num: '11', imgUrl: 'slash.png' },
    { name: '杀', pattern: 1, num: '2', imgUrl: 'slash.png' },
    { name: '杀', pattern: 1, num: '2', imgUrl: 'slash.png' },
    { name: '杀', pattern: 1, num: '13', imgUrl: 'slash.png' },
    { name: '杀', pattern: 0, num: '6', imgUrl: 'slash.png' },
    { name: '杀', pattern: 0, num: '7', imgUrl: 'slash.png' },
    { name: '杀', pattern: 0, num: '8', imgUrl: 'slash.png' },
    { name: '杀', pattern: 0, num: '9', imgUrl: 'slash.png' },
    { name: '杀', pattern: 0, num: '10', imgUrl: 'slash.png' },
    { name: '杀', pattern: 0, num: '13', imgUrl: 'slash.png' },
    { name: '闪', pattern: 1, num: '2', imgUrl: 'jink.png' },
    { name: '闪', pattern: 1, num: '2', imgUrl: 'jink.png' },
    { name: '闪', pattern: 1, num: '13', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '2', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '2', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '3', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '4', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '5', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '6', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '7', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '8', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '9', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '10', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '11', imgUrl: 'jink.png' },
    { name: '闪', pattern: 0, num: '11', imgUrl: 'jink.png' },
    { name: '桃', pattern: 1, num: '3', imgUrl: 'peach.png' },
    { name: '桃', pattern: 1, num: '4', imgUrl: 'peach.png' },
    { name: '桃', pattern: 1, num: '6', imgUrl: 'peach.png' },
    { name: '桃', pattern: 1, num: '7', imgUrl: 'peach.png' },
    { name: '桃', pattern: 1, num: '8', imgUrl: 'peach.png' },
    { name: '桃', pattern: 1, num: '9', imgUrl: 'peach.png' },
    { name: '桃', pattern: 1, num: '12', imgUrl: 'peach.png' },
    { name: '桃', pattern: 0, num: '12', imgUrl: 'peach.png' },
    { name: '诸葛连弩', pattern: 2, num: '1', imgUrl: 'crossbow.png' },
    { name: '诸葛连弩', pattern: 0, num: '1', imgUrl: 'crossbow.png' },
    { name: '雌雄双股剑', pattern: 3, num: '2', imgUrl: 'double_sword.png' },
    { name: '青釭剑', pattern: 3, num: '6', imgUrl: 'qinggang_sword.png' },
    { name: '青龙偃月刀', pattern: 3, num: '5', imgUrl: 'blade.png' },
    { name: '丈八蛇矛', pattern: 3, num: '12', imgUrl: 'spear.png' },
    { name: '贯石斧', pattern: 0, num: '5', imgUrl: 'axe.png' },
    { name: '方天画戟', pattern: 0, num: '12', imgUrl: 'halberd.png' },
    { name: '麒麟弓', pattern: 1, num: '5', imgUrl: 'kylin_bow.png' },
    { name: '八卦阵', pattern: 3, num: '2', imgUrl: 'eight_diagram.png' },
    { name: '八卦阵', pattern: 2, num: '2', imgUrl: 'eight_diagram.png' },
    { name: '绝影', pattern: 3, num: '5', imgUrl: 'jueying.png' },
    { name: '的卢', pattern: 2, num: '5', imgUrl: 'dilu.png' },
    { name: '爪黄飞电', pattern: 1, num: '13', imgUrl: 'zhuahuangfeidian.png' },
    { name: '赤兔', pattern: 1, num: '5', imgUrl: 'chitu.png' },
    { name: '大宛', pattern: 3, num: '13', imgUrl: 'dayuan.png' },
    { name: '紫骍', pattern: 0, num: '13', imgUrl: 'zixing.png' },
    { name: '五谷丰登', pattern: 1, num: '3', imgUrl: 'amazing_grace.png' },
    { name: '五谷丰登', pattern: 1, num: '4', imgUrl: 'amazing_grace.png' },
    { name: '桃园结义', pattern: 1, num: '1', imgUrl: 'god_salvation.png' },
    { name: '南蛮入侵', pattern: 3, num: '7', imgUrl: 'savage_ass1ult.png' },
    { name: '南蛮入侵', pattern: 3, num: '13', imgUrl: 's1v1ge_ass1ult.png' },
    { name: '南蛮入侵', pattern: 2, num: '7', imgUrl: 's1v1ge_ass1ult.png' },
    { name: '万箭齐发', pattern: 1, num: '1', imgUrl: 'archery_attack.png' },
    { name: '决斗', pattern: 3, num: '1', imgUrl: 'duel.png' },
    { name: '决斗', pattern: 2, num: '1', imgUrl: 'duel.png' },
    { name: '决斗', pattern: 0, num: '1', imgUrl: 'duel.png' },
    { name: '无中生有', pattern: 1, num: '7', imgUrl: 'ex_nihilo.png' },
    { name: '无中生有', pattern: 1, num: '8', imgUrl: 'ex_nihilo.png' },
    { name: '无中生有', pattern: 1, num: '9', imgUrl: 'ex_nihilo.png' },
    { name: '无中生有', pattern: 1, num: '11', imgUrl: 'ex_nihilo.png' },
    { name: '顺手牵羊', pattern: 3, num: '3', imgUrl: 'snatch.png' },
    { name: '顺手牵羊', pattern: 3, num: '4', imgUrl: 'snatch.png' },
    { name: '顺手牵羊', pattern: 3, num: '11', imgUrl: 'snatch.png' },
    { name: '顺手牵羊', pattern: 0, num: '4', imgUrl: 'snatch.png' },
    { name: '顺手牵羊', pattern: 0, num: '1', imgUrl: 'snatch.png' },
    { name: '过河拆桥', pattern: 3, num: '3', imgUrl: 'dismantlement.png' },
    { name: '过河拆桥', pattern: 3, num: '4', imgUrl: 'dismantlement.png' },
    { name: '过河拆桥', pattern: 3, num: '12', imgUrl: 'dismantlement.png' },
    { name: '过河拆桥', pattern: 2, num: '3', imgUrl: 'dismantlement.png' },
    { name: '过河拆桥', pattern: 2, num: '4', imgUrl: 'dismantlement.png' },
    { name: '过河拆桥', pattern: 1, num: '12', imgUrl: 'dismantlement.png' },
    { name: '借刀杀人', pattern: 2, num: '12', imgUrl: 'collateral.png' },
    { name: '借刀杀人', pattern: 2, num: '13', imgUrl: 'collateral.png' },
    { name: '无懈可击', pattern: 3, num: '11', imgUrl: 'nullification.png' },
    { name: '无懈可击', pattern: 2, num: '12', imgUrl: 'nullification.png' },
    { name: '无懈可击', pattern: 2, num: '13', imgUrl: 'nullification.png' },
    { name: '乐不思蜀', pattern: 3, num: '6', imgUrl: 'indulgence.png' },
    { name: '乐不思蜀', pattern: 2, num: '6', imgUrl: 'indulgence.png' },
    { name: '乐不思蜀', pattern: 1, num: '6', imgUrl: 'indulgence.png' },
    { name: '闪电', pattern: 3, num: '1', imgUrl: 'lightning.png' },
    { name: '寒冰剑', pattern: 3, num: '2', imgUrl: 'ice_sword.png' },
    { name: '仁王盾', pattern: 2, num: '2', imgUrl: 'renw1ng_shield.png' },
    { name: '闪电', pattern: 1, num: '12', imgUrl: 'lightning.png' },
    { name: '无懈可击', pattern: 0, num: '12', imgUrl: 'nullification.png' }
];
